### ISSUE TITLE
Missing ability to set CRUD dates

### ISSUE THREAD

**Issue by tobiassjosten** [contentful/contentful-management.php#159]
I'm wrapping up my migration to move a site to Contentful but one thing I can't figure out is how to set the correct created and updated dates. They're in the "system properties" of each entry but there's no way to set them and even if I hack something in (in the UpdatedAtTrait, for example), it doesn't seem to take effect when I look at the entry later on.

Is this an inability of the API or does the SDK do something to prevent me from setting these? What's a better approach to achieve what I'm trying to do?

Thanks in advance!

**Comment by pgrigoruta** [comment]
Hi @tobiassjosten , all meta-data is not writeable by design in the API. Some loose reference at https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/common-resource-attributes . The main idea is that sys reflects the internal state of Contentful, i.e. the time when the entry was created/updated in our system. If you need to store separate dates (assuming your own system's creation/update dates), please use normal custom fields.

**Comment by tobiassjosten** [comment]
That's a bit disappointing but well out of scope for the SDK. :) Thanks for the explanation, @pgrigoruta!
