### ISSUE TITLE
No possiblity to set id when creating an entry

### ISSUE THREAD

**Issue by michaelperrin** [contentful/contentful-management.php#96]
I would like to update a Contentful entry, knowing its id (that I retrieved from the Delivery API for instance).

There is currently no way to do it as it is not possible to create an `Entry` object with a given ID.

The constructor of the `Contentful\Management\Resource\Entry` object only accepts the Content type and initiates default system properties with it, with no possibility to add an ID.

I would propose to add a second argument to the constructor to add the ability to give an ID.

Should I open a PR if you agree with that?

**Comment by dborsatto** [comment]
Hey there,

you can actually do that already, but not the way you suggest.

The ID assignment happens when you call the API, not when constructing the object. This is done because conceptually A) the user should not be able to change a resource's ID B) a resource object should _not_ have an ID assigned until after it's been persisted in the API.

To use a custom ID, you have to specify a second parameter to the `create` method in the entry proxy. This method actually works on most resource types, when persisting an object.

``` php
$client->entry->create($entry, 'customId');
```

Bear in mind, the SDK is currently in beta and things are likely to change. The beta stage has been going on for a while (a bit too long, adittedly) because we were waiting for a new Contentful feature to be released, which will require a rewrite of a good chunk of the SDK in order to make it compatible. The good news is that the feature is almost here, so a final version of the SDK with a stable API is quickly approaching.

Cheers,

Davide

**Comment by michaelperrin** [comment]
Thanks @dborsatto for your answer.

I saw that in the documentation indeed. But here is my use case: I fetched an object from Contentful using the Contentful Delivery API using the SDK. I get a `Contentful\Delivery\DynamicEntry` as a result.

I would like to update the data of this entry. How can I do that?

**Comment by dborsatto** [comment]
Oh sorry, I misunderstood your initial question.

Well, first of all, the Delivery and Management API (and SDKs) work separately from each other, and you probably shouldn't mix their usage.

To update the data of an entry, just use the Management SDK:

``` php
/** @var \Contentful\Management\Resource\Entry $entry */
$entry = $client->entry->get($entryId);
// Do something with it
$entry->setField('fieldName', 'en-US', $someValue);
$entry->update();
```

Does this answer your question? 🙂

**Comment by michaelperrin** [comment]
Thanks again for your support.

That does work indeed and this is whayt I used as a workaround... But that makes yet another request to the API, for a resource that I already fetched (my id comes from the Delivery API, but it could be from any other source.).

My use case is the following: search in the Delivery API for a content with a given name (not id). If it is found, update it, otherwise create it (kind of upsert then 🙂)

**Comment by dborsatto** [comment]
If I may, why are you performing the search using the Delivery API? I think you could do the very same thing on the Management API, something like this:

``` php
try {
    $entry = $client->entry->get($entryId);
} catch (\Contentful\Exception\NotFoundException $exception) {
    $entry = new \Contentful\Management\Resource\Entry($contentTypeId);
}

// Do something
$this->setEntryData($entry);

if ($entry->getId()) {
    $entry->update();
} else {
    $client->entry->create($entry, $entryId);
}

```

Overall I think that mixing the use of Delivery API and Management API is not a good idea (there might be some data inconsistencies due to caching, you don't have parity in terms of features between the two, etc), so I suggest using just one SDK per feature/project 🙂

**Comment by michaelperrin** [comment]
I see your point, but the thing is that I am not trying to get the entry by its id, but by an other property (its title in my case)... hence the need of the 2 SDKs (I wish I could just use one).

**Comment by dborsatto** [comment]
The ability to filter entries in the Management API is the same as the Delivery API. If you're using a `Contentful\Delivery\Query` object in the CDA SDK, you can use the corresponding `Contentful\Management\Query` in the CMA SDK:

``` php
$query = (new \Contentful\Management\Query())
    ->setContentType($contentTypeId)
    ->where('fields.title', $someTitle)
    ->setLimit(1);

$entries = $client->entry->getAll($query);
$entry = $entries[0] ?? new \Contentful\Management\Resource\Entry($contentTypeId);
```

Does this not work for you?

**Comment by michaelperrin** [comment]
Amazing!! I didn't know I could query data from the Management SDK!
It seems to be the right way indeed. First tests seem fine.
I keep you posted in the afternoon.

**Comment by dborsatto** [comment]
That's great to hear!

If you need anything, feel free to open an issue on Github, open a support ticket, or write in our [Community forums](https://www.contentfulcommunity.com/) 🙂 

Davide

**Comment by michaelperrin** [comment]
I can confirm that the solution you provided me works 🙂

It was a bit confusing that the Management SDK has the same query features as the Delivery SDK.
There was no need for the feature I asked then (despite SDKs in other languages like JS seem to have it), so feel free to close this issue!

Thanks again for your help!

**Comment by dborsatto** [comment]
No problem 👍
